### ISSUE TITLE
Couple of security issues

### ISSUE THREAD

**Issue by bomberstudios** [YannickWidmer/sketch_strings_puller#1]
Hi there,

I've been taking a look at your plugin, and it does two things that are pretty scary:

1. it asks for username & password for GitHub, when it should be using OAuth or Personal Tokens (see https://developer.github.com/v3/auth/ for more info)
2. it stores the GitHub password in plain text format in the app's preferences, making it trivial for other apps & plugins to steal the information

Please consider fixing both things as soon as possible : )

**Comment by YannickWidmer** [comment]
So I switched to token instead of username password but I couldn't figure out how to store it securely. And as mentioned here I am not sure it is possible at all https://sketchplugins.com/d/134-best-strategy-for-locally-saving-user-data.

**Comment by YannickWidmer** [comment]
I added encription, however I need a key for it. So far I put it into the resources but I couldn't figure out if the resource folder can be obtained from the plugin or not. I used git-secret to hide it in git but if it is easy to get from the install location this is all vain.

**Comment by YannickWidmer** [comment]
I could find it and it is in plain text. I really don't know how to encrypt this since I seem not to be able to access the keychain from the app.

**Comment by YannickWidmer** [comment]
Now I generate the file on the first run with a random code. That is the best I can do. If there is possibility to do more please reopen.
